### ISSUE TITLE
Làm filter cho trang quản lí order

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#11]

**Comment by treasuryonly** [comment]
này ngoài ô search ra thì kế bên chắc để thêm cái dropdownlist để search theo tiêu chí phải không
:D

**Comment by treasuryonly** [comment]
fromdate todate
status
:D

**Comment by treasuryonly** [comment]
back-end có vẻ ổn rồi
đợi ngày gắn front-end
xD
