### ISSUE TITLE
Về áo nhóm Back To School

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#117]
click vào đặt áo nhóm anh thấy thế này: ĐA PHẦN CÁC NHÓM HỌ CHỈ CÓ Ý TƯỞNG CHỨ CHƯA CÓ THIẾT KẾ ĐẦU, MÌNH YÊU CẦU HỌ ATTACH HÌNH NHÓM VÀO THÌ HƠI KHÓ, THAY VÀO ĐÓ MÌNH CÓ 1 SỐ MẪU THIẾT KẾ SẴN HAY HỌ MÔ TẢ THÔNG TIN VÀ MÌNH HỖ TRỢ HỌ THIẾT KẾ RỒI MỚI IN KHÔNG THÌ SẼ RẤT KHÓ BÁN ÁO NHÓM)

Trích Sơn Tùng,

Mấy thánh cho ý kiến cái đi :|

**Comment by dacan2810** [comment]
thích thì thêm cũng chả sao. chủ yếu phải có đứa thiết kế rồi load hình lên mới dc. hỏi đứa nào thiết kế ấy. mà chọn hình sẵn là single choice hay multichoice ?
