### ISSUE TITLE
Đặt áo nhóm - back to school

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#119]
Khi chọn hoạ tiết có sẳn người dùng ko biết là mình đã chọn cái nào

**Comment by dacan2810** [comment]
chẳng lẽ lại phải in thêm cái họa tiết ra hả.

**Comment by tuanan94** [comment]
Cái nào đang được chọn thì có border cho nó

Sent from my iPhone

On Aug 30, 2016, at 10:17 PM, dacan2810 <notifications@github.com<mailto:notifications@github.com>> wrote:

chẳng lẽ lại phải in thêm cái họa tiết ra hả.

**Comment by dacan2810** [comment]
có border rồi nhưng chắc nhỏ quá nên ko thấy thôi
