### ISSUE TITLE
Thêm chọn màu và size cho áo

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#19]
tham khảo 

http://shop.aothun.vn/products/ao-thun-tron-4?mau=den

thêm filed màu và size vào bảng orderDetail

**Comment by treasuryonly** [comment]
xong
xD

**Comment by Nadreasky** [comment]
chưa có giao diện

**Comment by Nadreasky** [comment]
có giao diện òi, hàm lưu ok, nhưng mà chưa load lên đc
