### ISSUE TITLE
Làm lại trang giỏ hàng T.T

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#21]
![image](https://cloud.githubusercontent.com/assets/15942198/17170530/b21182bc-5416-11e6-975d-bdebe32872b1.png)
![image](https://cloud.githubusercontent.com/assets/15942198/17170570/e2b0f6aa-5416-11e6-93a7-6f095d5f0bda.png)

**Comment by treasuryonly** [comment]
Lazada có vẻ đẹp hơn
xD
