### ISSUE TITLE
Thêm nút "Thêm sản phẩm"

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#25]
Lúc remake lại trang quản lí product wên bỏ nó gòi =='

**Comment by Quannpmse61326** [comment]
Làm luôn 3 nút thêm, xóa, sửa luôn đi

**Comment by Nadreasky** [comment]
xóa sửa có òi, thiếu nút add thoy

**Comment by Nadreasky** [comment]
xong gòi nha
