### ISSUE TITLE
Làm cái gạch giá cũ fía trên giá hiện tại

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#40]
là cái này nek
![image](https://cloud.githubusercontent.com/assets/15942198/17329124/6786ce3a-58eb-11e6-89c6-a06d8f19a7ec.png)

**Comment by Quannpmse61326** [comment]
![capture](https://cloud.githubusercontent.com/assets/15978819/17359724/1440b41e-5992-11e6-986b-419894f6654b.PNG)
Xong

**Comment by Nadreasky** [comment]
chưa xong nhé, update xong thí nó chưa lên :v, làm lại giùm chút nhe :dancers:
