### ISSUE TITLE
Trang đại lí bị lỗi

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#56]
fải có index phía sau mới đc

**Comment by tuanan94** [comment]
Cái chức năng này là đặt hàng đại lí đúng ko?

Ko phải tuyển đại lý, Cho nên, chi thêm menu đặt hàng cho đại lí khi user đó là agency. Còn mục tuyển đại lí chỉ là trang để show thông tin tuyển dụng thôi
