### ISSUE TITLE
[Feedback]23_7_2016 Anh Tùng

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#6]
Hi Tuan An

Anh có ý kiến sau
1. Web mình thiếu dòng (All/ features....)
2. Khoảng cách giữa các phần trên và dưới, giữa 2 hình ảnh ngang 1 dòng gần nhau quá dẫ đến web nhìn trật trội 

Em cho bổ sung và chỉnh lại nhe

Anh cam on em

A Tung

**Comment by treasuryonly** [comment]
8-}
![github feedback 23 7 16](https://cloud.githubusercontent.com/assets/20497672/17078869/3843ec44-5129-11e6-96b7-4c4d44a52908.png)

**Comment by tuanan94** [comment]
=]] Ohm đúng rồi đó
