### ISSUE TITLE
Lỗi logo bên góc phải

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#67]
![screen shot 2016-08-10 at 5 03 56 pm](https://cloud.githubusercontent.com/assets/9337622/17549903/bca5ca7e-5f1c-11e6-9606-bc01ad8ae3c7.png)

Có 2 lỗi.
1. Màu tím
2. Click vào search => văng ra trang demo

**Comment by tuanan94** [comment]
Click vào logo cũng chết luon má ơi

**Comment by Nadreasky** [comment]
cái này sửa rồi mà chưa up cc
