### ISSUE TITLE
Làm URL writing

### ISSUE THREAD

**Issue by Nadreasky** [Nadreasky/BanleShop#7]
Hiện tại thì url có dạng là

yourfashion.com.vn/sanpham/1 với 1 là id của sản phẩm, 

Mình phải làm sao cho nó giống như web ngta là

yourfashion.com.vn/sanpham/tensanpham

Keyword là URL writing nha!

**Comment by Nadreasky** [comment]
còn dính id trong danh mục

**Comment by Quannpmse61326** [comment]
SEO fix #7
