### ISSUE TITLE
xây dựng giao diện để đặt áo nhóm.

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#86]
Phần này quan trọng vì phải hợp với ý tưởng của chương trình. Sẽ thảo luận trực tiếp

**Comment by tuanan94** [comment]
![screen shot 2016-08-15 at 8 37 00 pm](https://cloud.githubusercontent.com/assets/9337622/17665981/2a84c37e-6328-11e6-9c43-61f68125b787.png)

![screen shot 2016-08-15 at 8 37 07 pm](https://cloud.githubusercontent.com/assets/9337622/17665963/19f057ee-6328-11e6-85e8-fc70f4084245.png)

**Comment by Nadreasky** [comment]
còn back end và sửa lại front end chút đỉnh
