### ISSUE TITLE
Banner back to school

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#90]
Thêm vào mấy chữ tiếng Việt. lớp 12A2 - yêu lắm

Thêm text này vào: vui hơn mua 5 giảm 10%, mua 10 giảm 15%, mua trên 20 giảm 20%
background nên là hình ảnh mờ của trường học sẽ đẹp hơn.màu xanh lá cây đậm nhìn xấu quá - Sơn Tùng said

**Comment by Nadreasky** [comment]
Ko lẽ tao chửi, màu xanh lá cây đậm là màu của cái bảng mà -_-
