### ISSUE TITLE
Banner sales

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#91]
còn banner sales - tạm thời ngày launch mình sẽ hide di

**Comment by tuanan94** [comment]
thay bằng banner các tai nghe cá tính với dòng chữ " giá bất ngờ - rẻ nhất "

**Comment by Nadreasky** [comment]
banner sale là cái nào, fải cái này hok
![image](https://cloud.githubusercontent.com/assets/15942198/17669715/ef52033c-6338-11e6-9860-4d19c0bdb069.png)
