### ISSUE TITLE
Giá tốt nhất tuần

### ISSUE THREAD

**Issue by tuanan94** [Nadreasky/BanleShop#93]
Phần trăm giảm và 2 cái giá ko khớp 
![screen shot 2016-08-16 at 11 45 42 am](https://cloud.githubusercontent.com/assets/9337622/17688186/19448584-63a7-11e6-9d8f-55070cdd6b2c.png)

**Comment by Nadreasky** [comment]
cái này là demo, phải cho 1 cái chính thức thì đổi chớ j` đâu
